# Generated by Django 2.1.7 on 2019-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_table',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
