# Generated by Django 2.1.7 on 2019-03-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_shared_post_table_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.IntegerField(default=0)),
                ('post_id', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('solved', models.IntegerField(default=0)),
            ],
        ),
    ]
