# Generated by Django 2.1.7 on 2019-03-22 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_report_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='reported_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
