# Generated by Django 2.1.7 on 2019-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_report_table_reported_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_table',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shared_post_table',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report_table',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
