# Generated by Django 2.1.7 on 2019-03-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190322_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_table',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.poll_table'),
        ),
    ]
