# Generated by Django 2.1.7 on 2019-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190322_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_table',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
