# Generated by Django 2.1.7 on 2019-03-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190322_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll_table',
            name='reported',
        ),
        migrations.RemoveField(
            model_name='shared_post_table',
            name='reported',
        ),
    ]
