# Generated by Django 2.1.7 on 2019-03-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_notification_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification_table',
            name='post_type',
        ),
    ]
