# Generated by Django 2.1.7 on 2019-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190324_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_table',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
