# Generated by Django 2.1.7 on 2019-03-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_notification_table_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_table',
            old_name='post_id',
            new_name='type_id',
        ),
    ]
